bookshop_bookshop_homepage:
    pattern:  /
    defaults: { _controller: BookshopBookshopBundle:Page:index }
    
bookshop_bookshop_category:
    pattern:  /cid={cid}
    defaults: { _controller: BookshopBookshopBundle:Page:categoryPage }
    requirements:
       _method:  GET
       id: \d+

BookshopBookshopBundle_product_add:
    pattern:  /product
    defaults: { _controller: BookshopBookshopBundle:Cart:add }
    requirements:
        _method:  POST
      
        
BookshopBookshopBundle_product_remove:
    pattern:  /product_rm
    defaults: { _controller: BookshopBookshopBundle:Cart:remove }
    requirements:
        _method:  POST


BookshoBookshopBundle_cart:
    pattern: /cart
    defaults: { _controller: BookshopBookshopBundle:Cart:cartPage }
    
BookshopBookshopBundle_product_update:
    pattern:  /product_update
    defaults: { _controller: BookshopBookshopBundle:Cart:update }
    requirements:
        _method:  POST     
        
BookshopBookshopBundle_product_process:
    pattern:  /product_process
    defaults: { _controller: BookshopBookshopBundle:Cart:processForm }
    requirements:
        _method:  POST    
        
BookshopBookshopBundle_checkout_billing:
    pattern: /checkout_billing
    defaults: { _controller: BookshopBookshopBundle:Checkout:show }
    
BookshopBookshopBundle_checkout_shipping:
    pattern: /checkout_shipping
    defaults: { _controller: BookshopBookshopBundle:Checkout:checkoutShipping }
    requirements:
      _method: POST
BookshopBookshopBundle_checkout_shippingMethod:
    pattern: /checkout_shippingMethod
    defaults: { _controller: BookshopBookshopBundle:Checkout:shippingMethod }
    requirements:
      _method: POST
BookshopBookshopBundle_checkout_billingMethod:
    pattern: /checkout_billingMethod
    defaults: { _controller: BookshopBookshopBundle:Checkout:billingMethod }
    requirements:
      _method: POST
      
BookshopBooskhopBundle_checkout_success:
    pattern: /checkout_success
    defaults: { _controller: BookshopBookshopBundle:Checkout:success }
    requirements:
      _method: POST