<?php

namespace Bookshop\BookshopBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ShippingMethodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShippingMethodRepository extends EntityRepository {

    public function getShippingMethod($Id) {
        $qd = $this->createQueryBuilder('c')
                ->select('c')
                ->where('c.id= :id')
                ->setParameter('id', $Id);
        return $qd->getQuery()
                        ->getOneOrNullResult();
    }

}
